import { ThaiChar, CardType, ThaiClass } from './types';

export const consonants: ThaiChar[] = [
  { char: 'ก', name: 'Gor Kai', phonetic: 'k', meaning: 'Chicken', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'ไก่', exampleMeaning: 'Chicken' },
  { char: 'ข', name: 'Khor Khai', phonetic: 'kh', meaning: 'Egg', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ไข่', exampleMeaning: 'Egg' },
  { char: 'ฃ', name: 'Khor Khuat', phonetic: 'kh', meaning: 'Bottle (Obsolete)', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ขวด', exampleMeaning: 'Bottle' },
  { char: 'ค', name: 'Khor Khwai', phonetic: 'kh', meaning: 'Buffalo', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ควาย', exampleMeaning: 'Buffalo' },
  { char: 'ฅ', name: 'Khor Khon', phonetic: 'kh', meaning: 'Person (Obsolete)', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'คน', exampleMeaning: 'Person' },
  { char: 'ฆ', name: 'Khor Ra-khang', phonetic: 'kh', meaning: 'Bell', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ระฆัง', exampleMeaning: 'Bell' },
  { char: 'ง', name: 'Ngor Ngu', phonetic: 'ng', meaning: 'Snake', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'งู', exampleMeaning: 'Snake' },
  { char: 'จ', name: 'Jor Jan', phonetic: 'j', meaning: 'Plate', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'จาน', exampleMeaning: 'Plate' },
  { char: 'ฉ', name: 'Chor Ching', phonetic: 'ch', meaning: 'Cymbals', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ฉิ่ง', exampleMeaning: 'Cymbals' },
  { char: 'ช', name: 'Chor Chang', phonetic: 'ch', meaning: 'Elephant', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ช้าง', exampleMeaning: 'Elephant' },
  { char: 'ซ', name: 'Sor So', phonetic: 's', meaning: 'Chain', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'โซ่', exampleMeaning: 'Chain' },
  { char: 'ฌ', name: 'Chor Cher', phonetic: 'ch', meaning: 'Tree', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'เฌอ', exampleMeaning: 'Tree' },
  { char: 'ญ', name: 'Yor Ying', phonetic: 'y', meaning: 'Woman', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'หญิง', exampleMeaning: 'Woman' },
  { char: 'ฎ', name: 'Dor Cha-da', phonetic: 'd', meaning: 'Headdress', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'ชฎา', exampleMeaning: 'Headdress' },
  { char: 'ฏ', name: 'Tor Pa-tak', phonetic: 't', meaning: 'Goad/Spear', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'ปฏัก', exampleMeaning: 'Goad' },
  { char: 'ฐ', name: 'Thor Than', phonetic: 'th', meaning: 'Pedestal', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ฐาน', exampleMeaning: 'Base' },
  { char: 'ฑ', name: 'Thor Montho', phonetic: 'th', meaning: 'Character Montho', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'มณโฑ', exampleMeaning: 'Montho' },
  { char: 'ฒ', name: 'Thor Phu-thao', phonetic: 'th', meaning: 'Elder', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ผู้เฒ่า', exampleMeaning: 'Elder' },
  { char: 'ณ', name: 'Nor Nen', phonetic: 'n', meaning: 'Novice Monk', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'เณร', exampleMeaning: 'Novice Monk' },
  { char: 'ด', name: 'Dor Dek', phonetic: 'd', meaning: 'Child', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'เด็ก', exampleMeaning: 'Child' },
  { char: 'ต', name: 'Tor Tao', phonetic: 't', meaning: 'Turtle', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'เต่า', exampleMeaning: 'Turtle' },
  { char: 'ถ', name: 'Thor Thung', phonetic: 'th', meaning: 'Sack', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ถุง', exampleMeaning: 'Sack' },
  { char: 'ท', name: 'Thor Thahan', phonetic: 'th', meaning: 'Soldier', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ทหาร', exampleMeaning: 'Soldier' },
  { char: 'ธ', name: 'Thor Thong', phonetic: 'th', meaning: 'Flag', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ธง', exampleMeaning: 'Flag' },
  { char: 'น', name: 'Nor Nu', phonetic: 'n', meaning: 'Mouse', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'หนู', exampleMeaning: 'Mouse' },
  { char: 'บ', name: 'Bor Baimai', phonetic: 'b', meaning: 'Leaf', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'ใบไม้', exampleMeaning: 'Leaf' },
  { char: 'ป', name: 'Por Pla', phonetic: 'p', meaning: 'Fish', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'ปลา', exampleMeaning: 'Fish' },
  { char: 'ผ', name: 'Phor Phueng', phonetic: 'ph', meaning: 'Bee', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ผึ้ง', exampleMeaning: 'Bee' },
  { char: 'ฝ', name: 'For Fa', phonetic: 'f', meaning: 'Lid', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ฝา', exampleMeaning: 'Lid' },
  { char: 'พ', name: 'Phor Phan', phonetic: 'ph', meaning: 'Tray', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'พาน', exampleMeaning: 'Tray' },
  { char: 'ฟ', name: 'For Fan', phonetic: 'f', meaning: 'Teeth', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ฟัน', exampleMeaning: 'Teeth' },
  { char: 'ภ', name: 'Phor Sam-phao', phonetic: 'ph', meaning: 'Sailboat', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'สำเภา', exampleMeaning: 'Sailboat' },
  { char: 'ม', name: 'Mor Ma', phonetic: 'm', meaning: 'Horse', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ม้า', exampleMeaning: 'Horse' },
  { char: 'ย', name: 'Yor Yak', phonetic: 'y', meaning: 'Giant', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ยักษ์', exampleMeaning: 'Giant' },
  { char: 'ร', name: 'Ror Ruea', phonetic: 'r', meaning: 'Boat', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'เรือ', exampleMeaning: 'Boat' },
  { char: 'ล', name: 'Lor Ling', phonetic: 'l', meaning: 'Monkey', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'ลิง', exampleMeaning: 'Monkey' },
  { char: 'ว', name: 'Wor Waen', phonetic: 'w', meaning: 'Ring', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'แหวน', exampleMeaning: 'Ring' },
  { char: 'ศ', name: 'Sor Sala', phonetic: 's', meaning: 'Pavilion', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ศาลา', exampleMeaning: 'Pavilion' },
  { char: 'ษ', name: 'Sor Rue-si', phonetic: 's', meaning: 'Hermit', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'ฤๅษี', exampleMeaning: 'Hermit' },
  { char: 'ส', name: 'Sor Suea', phonetic: 's', meaning: 'Tiger', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'เสือ', exampleMeaning: 'Tiger' },
  { char: 'ห', name: 'Hor Hip', phonetic: 'h', meaning: 'Chest/Box', class: ThaiClass.HIGH, type: CardType.CONSONANT, exampleWord: 'หีบ', exampleMeaning: 'Chest' },
  { char: 'ฬ', name: 'Lor Chu-la', phonetic: 'l', meaning: 'Kite', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'จุฬา', exampleMeaning: 'Kite' },
  { char: 'อ', name: 'Or Ang', phonetic: 'o', meaning: 'Basin', class: ThaiClass.MID, type: CardType.CONSONANT, exampleWord: 'อ่าง', exampleMeaning: 'Basin' },
  { char: 'ฮ', name: 'Hor Nok-huk', phonetic: 'h', meaning: 'Owl', class: ThaiClass.LOW, type: CardType.CONSONANT, exampleWord: 'นกฮูก', exampleMeaning: 'Owl' },
];

export const vowels: ThaiChar[] = [
  { char: 'ะ', name: 'Sara A', phonetic: 'a', meaning: 'Short A', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'กะ', exampleMeaning: 'Ka (Shift)' },
  { char: 'า', name: 'Sara Aa', phonetic: 'aa', meaning: 'Long A', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'มา', exampleMeaning: 'Come' },
  { char: 'ิ', name: 'Sara I', phonetic: 'i', meaning: 'Short I', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ติ', exampleMeaning: 'Criticize' },
  { char: 'ี', name: 'Sara Ii', phonetic: 'ii', meaning: 'Long I', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'มี', exampleMeaning: 'Have' },
  { char: 'ึ', name: 'Sara Ue', phonetic: 'ue', meaning: 'Short Ue', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'หึ', exampleMeaning: 'Huh?' },
  { char: 'ื', name: 'Sara Uue', phonetic: 'uue', meaning: 'Long Ue', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'มือ', exampleMeaning: 'Hand' },
  { char: 'ุ', name: 'Sara U', phonetic: 'u', meaning: 'Short U', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ดุ', exampleMeaning: 'Fierce' },
  { char: 'ู', name: 'Sara Uu', phonetic: 'uu', meaning: 'Long U', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'ดู', exampleMeaning: 'Look' },
  { char: 'เะ', name: 'Sara E', phonetic: 'e', meaning: 'Short E', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'เตะ', exampleMeaning: 'Kick' },
  { char: 'เ', name: 'Sara Ee', phonetic: 'ee', meaning: 'Long E', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'เท', exampleMeaning: 'Pour' },
  { char: 'แะ', name: 'Sara Ae', phonetic: 'ae', meaning: 'Short Ae', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'แกะ', exampleMeaning: 'Sheep' },
  { char: 'แ', name: 'Sara Aae', phonetic: 'aae', meaning: 'Long Ae', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'แม', exampleMeaning: 'Mother (dialect)' },
  { char: 'โะ', name: 'Sara O', phonetic: 'o', meaning: 'Short O', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'โต๊ะ', exampleMeaning: 'Table' },
  { char: 'โ', name: 'Sara Oo', phonetic: 'oo', meaning: 'Long O', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'โต', exampleMeaning: 'Big' },
  { char: 'เาะ', name: 'Sara Or', phonetic: 'or', meaning: 'Short Or', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'เกาะ', exampleMeaning: 'Island' },
  { char: 'อ', name: 'Sara Oor', phonetic: 'oor', meaning: 'Long Or', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'รอ', exampleMeaning: 'Wait' },
  { char: 'เอะ', name: 'Sara Oe', phonetic: 'oe', meaning: 'Short Oe', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'เจอะ', exampleMeaning: 'Meet' },
  { char: 'เ อ', name: 'Sara Ooe', phonetic: 'ooe', meaning: 'Long Oe', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'เจอ', exampleMeaning: 'Found' },
  { char: 'เียะ', name: 'Sara Ia', phonetic: 'ia', meaning: 'Short Ia', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'เกียะ', exampleMeaning: 'Wooden shoe' },
  { char: 'เีย', name: 'Sara Iia', phonetic: 'iia', meaning: 'Long Ia', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'เลีย', exampleMeaning: 'Lick' },
  { char: 'เือะ', name: 'Sara Uea', phonetic: 'uea', meaning: 'Short Uea', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ผัวะ', exampleMeaning: 'Sound of striking' },
  { char: 'เือ', name: 'Sara Uuea', phonetic: 'uuea', meaning: 'Long Uea', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'เสือ', exampleMeaning: 'Tiger' },
  { char: 'ัวะ', name: 'Sara Ua', phonetic: 'ua', meaning: 'Short Ua', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ผัวะ', exampleMeaning: 'Slap sound' },
  { char: 'ัว', name: 'Sara Uua', phonetic: 'uua', meaning: 'Long Ua', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'วัว', exampleMeaning: 'Cow' },
  { char: 'ำ', name: 'Sara Am', phonetic: 'am', meaning: 'Am', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'จำ', exampleMeaning: 'Remember' },
  { char: 'ใ', name: 'Sara Ai Mai Muan', phonetic: 'ai', meaning: 'Ai (Rolled)', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ใจ', exampleMeaning: 'Heart' },
  { char: 'ไ', name: 'Sara Ai Mai Malai', phonetic: 'ai', meaning: 'Ai (Malai)', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ไป', exampleMeaning: 'Go' },
  { char: 'เา', name: 'Sara Ao', phonetic: 'ao', meaning: 'Ao', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'เรา', exampleMeaning: 'We' },
  { char: 'ฤ', name: 'Rue', phonetic: 'rue', meaning: 'Rue', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: 'ฤดู', exampleMeaning: 'Season' },
  { char: 'ฤๅ', name: 'Rue', phonetic: 'ruue', meaning: 'Long Rue', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: 'ฤๅ', exampleMeaning: 'Or/Whether' },
  { char: 'ฦ', name: 'Lue', phonetic: 'lue', meaning: 'Lue (Obsolete)', class: ThaiClass.VOWEL_SHORT, type: CardType.VOWEL, exampleWord: '-', exampleMeaning: '-' },
  { char: 'ฦๅ', name: 'Lue', phonetic: 'luue', meaning: 'Long Lue (Obsolete)', class: ThaiClass.VOWEL_LONG, type: CardType.VOWEL, exampleWord: '-', exampleMeaning: '-' },
];
